# Generated by Django 4.2.24 on 2025-09-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
