services:
  db:
    image: postgres:12-bullseye
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: "timetracker"
      POSTGRES_USER: "myadmin"
      POSTGRES_PASSWORD: "Adm!nP@ssword"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: